using NotTwice.Events.Runtime.ScriptableObjects.Events;
using NotTwice.Events.Runtime.Serializables.Abstract;
using System;

namespace SteamworksPlus.Runtime.Serializables
{
    /// <summary>
    /// Callback used to interpret an error generated by a Steam process
    /// </summary>
    [Serializable]
    public class SPErrorCallback : NTGenericEventTypeSwitcher<NTStringGameEvent, string>
	{
	}
}
